name: Scrape latest data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Scrape data
        run: |
          ./script.sh
      - name: Commit and push files
        run: |
          git config --local user.name "AutoBot"
          git config --local user.email "actions@noreply.github.com"
          git add .
          git commit -m "Update data"
          git push
