name: Update database

on:
  workflow_run:
    workflows: ["Scrape latest data"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install python dependencies
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: pip
      - run: pip3 install -r requirements.txt
      - name: Update database
        env:
          MONGOURL: ${{ secrets.MONGOURL }}
        run: |
          python3 web_database.py
