name: Update database

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install python dependencies
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: pip
      - run: pip3 install -r requirements.txt
      - name: Update database
        env:
          MONGOURL: ${{ secrets.MONGOURL }}
        run: |
          python3 web_database.py
